#pragma once

enum DIR { DIR_UP, DIR_UPL, DIR_UPR, DIR_DOWN, DIR_DOWNL,DIR_DOWNR, DIR_LEFT, DIR_RIGHT, DIR_END };

enum OBJID { DIRT, WATER, SEED, OBJ, INVEN, PLAYER,HORSE,MONSTER, BULLET, BUTTON, UIIMG, /* BULLET, MONSTER, MOUSE, SHIELD*/END };

enum SCENEID { SC_MENU, SC_HOUSE, SC_FARM, SC_NIGHT,SC_STORE, SC_CAVE,SC_ENDING,SC_UNDERTALE,SC_RUNNING, SC_END };

enum STATE { IDLE, WALK, ATTACK, HIT, DEAD, STATE_END };

enum ITEMID { PICK, WATERING, PICKAX, AX, PARSNIPSEED, PARSNIP, WOOD, ROCK,PRESENT,GUN, TREE,APPLE,CRYSTAL,KEG,PICKLE,STATUE,SALAD,PUZZLE,BAN,BOX,ITEM_END };

enum DIRT{SOLO, DOWNRIGHT, DLR, DOWNLEFT, DOWN, UDR, UDLR, UDL, UPDOWN, UPRIGHT, ULR, UPLEFT, UP,RIGHT,LEFTRIGHT, LEFT, D_END};